#+OPTIONS: ':nil *:t -:t ::t <:t H:3 \n:nil ^:t arch:headline author:t c:nil
#+OPTIONS: creator:comment d:(not "LOGBOOK") date:t e:t email:nil f:t inline:t
#+OPTIONS: num:t p:nil pri:nil prop:nil stat:t tags:t tasks:t tex:t timestamp:t
#+OPTIONS: toc:nil todo:t |:t
#+TITLE: Exercise 2 - Treasure Hunt
#+DATE: 2015-05-18
#+AUTHOR: Sebastian Hahn
#+EMAIL: sebastian.hahn@geo.tuwien.ac.at
#+DESCRIPTION:
#+KEYWORDS:
#+LANGUAGE: en
#+SELECT_TAGS: export
#+EXCLUDE_TAGS: noexport
#+CREATOR: Emacs 24.4.1 (Org mode 8.3beta)
#+LATEX_CLASS: article
#+LATEX_CLASS_OPTIONS:
#+LATEX_HEADER:
#+LATEX_HEADER_EXTRA:

* Treasure Hunt
The second exercise will be a treasure hunt based on your common sense and
ability to work with files, arrays and plotting functions. In general, a
treasure hunt is one of many different types of games which can have one or more
players who try to find hidden articles, locations or places by using a series
of clues. Treasure hunt games may be an indoor or outdoor activity. Outdoors
they can be played in a garden or the treasure could be located anywhere around
the world. Probably you have heard about Geocaching, which is an outdoor
treasure-hunting game in which the participants use a global positioning system
(GPS) receiver or other navigational techniques to hide and seek containers
(called "geocaches" or "caches") anywhere in the world. However, this time the
game takes place in the virtual world, where bytes, bits and mainly your Python
skill are important.

** Game instructions
The following treasure hunt is based on files (e.g. .csv, .npy, .nc) and their
content. All files can be downloaded from http://rs.geo.tuwien.ac.at/cpa/,
however, you will only be able to download a file once knowing its correct
file name. The file name, column name, variable name or row position are
concealed in riddles, quotes or 
 
** Clues
1. Please download and open <filename1> with your preferred reader. In
   <column1> at row number <row1>

   If you can find the right answer to the following riddle you have found
   <filename1>

   - /It has 4 legs but cannot walk?/
   
   Complete the following movie quote and you have found <column1>:

   - /May the <column1> be with you, Han Solo/

3. 

4. Please download <filename3>, which is a treasure map. Read and plot the
   variable <variable3>. Which continent is missing? The answer to this
   questions will give you <filename4_part2>.

5. Please download <filename4_part1>_<filename4_part2>


* Program Interface
1. The program should start by asking the player for the following information:
   - Name
   - Amount of money they brought to the Roulette table.
2. After that the program should ask for the type of bet the player wants to
   play (see list above). Show the options to the player. Also include an option
   to quit the program.
3. When a bet type is selected ask for the bet. Depending on the bet this input 
   will have different meanings so list the possibilities to the player. Make
   sure the player does not bet more money than he has.
4. "Rotate" the Roulette wheel and show the result to the player. Also show the
   amount won or lost and the updated amount of money the player has left. Start
   again at step 2.

* Python hints
All needed modules an data structures can be found in the Python standard library.

** Useful code snippets
#+caption: This snippet clears the screen of a terminal
#+begin_src python
import os
os.system('cls' if os.name == 'nt' else 'clear')
#+end_src

* Reporting
The following is required when handing in the exercise:
- A short (1-3) pages report explaining what the program is doing, its structure and how the
  functions and/or modules work together. Somebody reading this document should
  find it easy to start reading the source code. *No source code* in this
  document. This can also be a simple README text file.
- *Documented* python source code.

After I had a chance to look at the source code I will make appointments with
each group to have a short (10-15 min) talk about the exercise.
Hand in of the exercise will be handled in TUWEL.

** Due Date
Please hand in the exercise by 2015-06-08.



